# Dockerfile.airflow
FROM apache/airflow:3.1.0

# 1. Ставим JDK (нужен для Spark)
USER root
RUN apt-get update && \
    apt-get install -y default-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Копируем requirements.txt и устанавливаем зависимости
USER airflow
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
