# Dockerfile.airflow
FROM apache/airflow:3.1.0

# 1. Ставим JDK (нужен для Spark)
USER root
RUN apt-get update && \
    apt-get install -y default-jdk && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Ставим провайдер Spark, Trino и pyspark в образ
USER airflow
RUN pip install --no-cache-dir polars>=0.20.0 minio>=7.2.0 \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-trino \
    pyspark
