version: '3.2'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    environment:
      MINIO_ROOT_USER: miniominio
      MINIO_ROOT_PASSWORD: miniominio
    volumes:
      - minio_data:/data
    ports:
      - "9001:9001"
      - "9000:9000"
    command: minio server /data --console-address ":9001"
    networks:
      - bdproject_default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  minio_data:
    driver: local

networks:
  bdproject_default:
    external: true